CREATE TABLE TOPSTORY (
  id INT NOT NULL,
  title VARCHAR(255),
  url VARCHAR(255),
  score INT,
  time BIGINT,
  by VARCHAR(255),  
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);